# Generated by Django 5.0.6 on 2024-05-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter client name', max_length=100, null=True, verbose_name='Client name')),
                ('username', models.CharField(blank=True, help_text='Enter client username', max_length=100, null=True, verbose_name='Client username')),
                ('telegram_id', models.CharField(help_text='Enter telegram ID', max_length=30, unique=True, verbose_name='Telegram ID')),
                ('language', models.CharField(blank=True, default='uz', help_text='Enter client system language', max_length=10, null=True, verbose_name='Client System Language')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
